USE [SIEF]
GO

/* TABLAS */

GRANT SELECT, INSERT, UPDATE, DELETE, DELETE ON dbo.CUENTA_COBRAR_NO_ASOCIADA_OPERACION TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_OPERACION_GRAVAMEN TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GRAVAMEN_FIDEICOMETIDO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_FIDUCIARIA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_CREDITO_SINDICADO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_DOCUMENTO_CARTA_CREDITO_IMPORTACION_POLIZA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_SALDO_CUENTA_COBRAR TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_FIDEICOMETIDA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.BIEN_REALIZABLE_OPERACION_CREDITO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_OPERACION_GRAVAMEN_FIDEICOMETIDO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_OPERACION_LISTA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_OPERACION_PRIORIDAD TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_REAL_POLIZA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_ORIGEN_RECURSO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_OPERACION_ESPECIAL TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_OPERACION_CANCELADA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_NATURALEZA_GASTO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_MODIFICACION TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_CODEUDOR TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_ACTIVIDAD_ECONOMICA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_FIDEICOMISO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_FACTURA_CEDIDA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_DOCUMENTO_CARTA_CREDITO_IMPORTACION TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_CARTA_CREDITO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_VALOR TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_REAL TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.GARANTIA_OPERACION TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.BIEN_REALIZABLE_NO_REPORTADO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.BIEN_REALIZABLE TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_NO_REPORTADA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.CUOTA_ATRASADA TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OPERACION_CREDITO_DIRECTO_INDIRECTO TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.DEUDOR TO RAP_AccesoSICAD
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.PERSONA TO RAP_AccesoSICAD
GO








