USE [SICAD_HISTORICO]
GO

/* TABLAS */

GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_201506 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_NO_REPORTADOS_0 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_NO_REPORTADOS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_NO_REPORTADOS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_OPERACIONES_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_OPERACIONES_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BIENES_REALIZABLES_OPERACIONES_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BITACORA_PROCESO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BITACORA_PROCESO_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CONFIGURACION_SISTEMA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CUENTAS_COBRAR_NO_ASOCIADAS_OPERACIONES_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CUENTAS_COBRAR_NO_ASOCIADAS_OPERACIONES_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CUENTAS_COBRAR_NO_ASOCIADAS_OPERACIONES_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CUOTAS_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CUOTAS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CUOTAS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CUOTAS_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DEUDORES_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DEUDORES_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DEUDORES_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DEUDORES_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DEUDORES_RECALIFICADOS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DEUDORES_RECALIFICADOS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DEUDORES_RECALIFICADOS_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ENCABEZADO_XML_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ENCABEZADO_XML_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ENTIDAD_CONTABLE_ESTADOS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ENTIDAD_CONTABLE_ESTADOS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_GRAVAMEN_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_GRAVAMEN_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_GRAVAMEN_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_GRAVAMEN_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_GRAVAMEN_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_GRAVAMEN_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_LISTA_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_LISTA_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_LISTA_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_LISTA_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_PRIORIDAD_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_PRIORIDAD_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIA_OPERACION_PRIORIDAD_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_CARTA_CREDITO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_CARTA_CREDITO_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_CARTA_CREDITO_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION_POLIZA_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION_POLIZA_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION_POLIZA_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FACTURAS_CEDIDAS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FACTURAS_CEDIDAS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FACTURAS_CEDIDAS_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMISO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMISO_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMISO_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA_GRAVAMEN_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA_GRAVAMEN_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA_GRAVAMEN_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDUCIARIAS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDUCIARIAS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_FIDUCIARIAS_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_POLIZA_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_POLIZA_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_REALES_POLIZA_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_VALORES_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_VALORES_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GARANTIAS_VALORES_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.HISTORICO_PROCESO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.HISTORICO_PROCESO_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.LOG_GARANTIAS_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.LOG_GARANTIAS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.LOG_GARANTIAS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.LOG_GARANTIAS_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_201504 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_ACTIVIDAD_ECONOMICA_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_ACTIVIDAD_ECONOMICA_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_ACTIVIDAD_ECONOMICA_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_CODEUDORES_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_CODEUDORES_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_CODEUDORES_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_CREDITO_SINDICADO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_CREDITO_SINDICADO_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_CREDITO_SINDICADO_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_MODIFICACION_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_MODIFICACION_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_MODIFICACION_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_MODIFICACION_OPERACIONES_CANCELADAS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_MODIFICACION_OPERACIONES_CANCELADAS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_MODIFICACION_OPERACIONES_CANCELADAS_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_NATURALEZA_GASTO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_NATURALEZA_GASTO_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_NATURALEZA_GASTO_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_NO_REPORTADAS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_NO_REPORTADAS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_NO_REPORTADAS_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_OPERACION_ESPECIAL_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_OPERACION_ESPECIAL_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_OPERACION_ESPECIAL_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_OPERACION_ESPECIAL_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_ORIGEN_RECURSOS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_ORIGEN_RECURSOS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_ORIGEN_RECURSOS_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_SALDOS_CUENTAS_COBRAR_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_SALDOS_CUENTAS_COBRAR_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_SALDOS_CUENTAS_COBRAR_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PERSONAS_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PERSONAS_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PERSONAS_201602 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_COMPORTAMIENTO_PAGO_HISTORICO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_COMPORTAMIENTO_PAGO_HISTORICO_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_EMISION_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_EMISION_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_EMISOR_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_EMISOR_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_FISICA_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_FISICA_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_INSTRUMENTO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_INSTRUMENTO_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_JURIDICA_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SUGEF_PADRON_JURIDICA_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_CALCULOS_MONTO_TOTAL_ADEUDADO_0 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_CALCULOS_MONTO_TOTAL_ADEUDADO_201502 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_CALCULOS_MONTO_TOTAL_ADEUDADO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_CALCULOS_MONTO_TOTAL_ADEUDADO_201601 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_RESP_CALCULOS_MONTO_TOTAL_ADEUDADO_201503 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TMP_RESP_CALCULOS_MONTO_TOTAL_ADEUDADO_201601 TO RAP_AccesoIntegracion
GO
