/*
Deployment script for SICAD_BITACORA

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName SICAD_BITACORA
:setvar DefaultFilePrefix SICAD_BITACORA
:setvar DefaultDataPath "G:\SQL2012\"
:setvar DefaultLogPath "F:\SQL2012\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf', SIZE = 78848KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf', SIZE = 4672KB , MAXSIZE = 2048GB , FILEGROWTH = 10%) COLLATE Latin1_General_CS_AS
GO

IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET COMPATIBILITY_LEVEL = 110
            WITH ROLLBACK IMMEDIATE;
    END


GO

IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS OFF,
                ANSI_PADDING OFF,
                ANSI_WARNINGS OFF,
                ARITHABORT OFF,
                CONCAT_NULL_YIELDS_NULL OFF,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER OFF,
                ANSI_NULL_DEFAULT OFF,
                CURSOR_DEFAULT GLOBAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY CHECKSUM,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO


IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET MULTI_USER
            WITH ROLLBACK IMMEDIATE;
    END


GO

ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_WRITE
            WITH ROLLBACK IMMEDIATE;
    END


GO

USE [$(DatabaseName)];


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating TABLES...';
GO


/****** Object:  Table [dbo].[BITACORA_2016]    Script Date: 17/05/2016 03:57:53 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BITACORA_2016](
	[ID_BITACORA] [int] IDENTITY(1,1) NOT NULL,
	[ID_ACCION] [int] NULL,
	[ID_MODULO] [int] NULL,
	[COD_ACCION] [int] NULL,
	[COD_MODULO] [int] NULL,
	[COD_EMPRESA] [int] NULL,
	[COD_SISTEMA] [varchar](20) NULL,
	[COD_USUARIO] [varchar](20) NULL,
	[ANO] [int] NULL,
	[DATO_ACTUALIZADO] [varchar](8000) NULL,
	[DATO_ELIMINADO] [varchar](8000) NULL,
	[DATO_NUEVO] [varchar](8000) NULL,
	[DES_REGISTRO] [varchar](4000) NULL,
	[FECHA] [int] NULL,
	[FECHA_HORA] [datetime] NULL,
	[HORA] [varchar](8) NULL,
	[MES] [int] NULL,
	[IP_ORIGEN] [varchar](15) NULL,
	[OFICINA_TX] [int] NULL,
	[TERMINAL_TX] [varchar](12) NULL,
	[MCADDR_TX] [varchar](20) NULL,
	[MONTO_TX] [numeric](20, 0) NULL,
 CONSTRAINT [PK_BITACORAS_2016] PRIMARY KEY CLUSTERED 
(
	[ID_BITACORA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO



PRINT N'Creating STORED PROCEDURES...';
GO


/****** Object:  StoredProcedure [dbo].[Bitacora_Inserta]    Script Date: 17/05/2016 03:58:34 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

/*
Bitacora_Inserta
Autor(es): GrupoMAS - Genoveva Salmeron
Fecha creación: FEB2015
Versión: 1.0
Descripción: Procedimiento almacenado que inserta en la bitácora la información del proceso ejecutado
Sistema(s): SICAD

Historial de cambios:

*/

CREATE PROCEDURE [dbo].[Bitacora_Inserta]
(	@piCOD_ACCION		INT,
	@piCOD_MODULO		INT,
	@piCOD_EMPRESA		INT,
	@psCOD_SISTEMA		VARCHAR (20),
	@psCOD_USUARIO		VARCHAR (20),	
	@psDATO_NUEVO		VARCHAR(MAX),
	@psDATO_ACTUALIZADO	VARCHAR(MAX),
	@psDATO_ELIMINADO	VARCHAR(MAX),
	@psDES_REGISTRO		VARCHAR(8000))
AS

BEGIN
	DECLARE @csNOMBRE_BASE_DATOS	VARCHAR (50),
			@csSENTENCIA_INSERTAR	VARCHAR(MAX),
			@vsNOMBRE_TABLA			VARCHAR (50),
			@viID_MODULO			INT,		
			@viID_ACCION			INT

	SET	@csNOMBRE_BASE_DATOS = 'SICAD_BITACORA'
	SET	@vsNOMBRE_TABLA		 = 'BITACORA_' + CONVERT(VARCHAR,DATEPART(YEAR,GETDATE()))
	
	SELECT	@viID_MODULO = ID_MODULO
	FROM	[SICAD_CONFIGURACION].dbo.AUDI_MODULO 
	WHERE	COD_MODULO = @piCOD_MODULO
	
	SELECT	@viID_ACCION = ID_ACCION 
	FROM	[SICAD_CONFIGURACION].dbo.AUDI_ACCION
	WHERE	COD_ACCION = @piCOD_ACCION

	SELECT @csSENTENCIA_INSERTAR =
	'INSERT INTO ' + @csNOMBRE_BASE_DATOS + '.[dbo].' + @vsNOMBRE_TABLA +
	'(
		ID_ACCION
		,ID_MODULO
		,COD_ACCION
	    ,COD_MODULO
	    ,COD_EMPRESA
	    ,COD_SISTEMA		
		,COD_USUARIO
		,ANO
		,DATO_ACTUALIZADO
		,DATO_ELIMINADO
		,DATO_NUEVO	
		,DES_REGISTRO
		,FECHA
		,FECHA_HORA
		,HORA
		,MES	
	) VALUES('	
		+CONVERT(VARCHAR,ISNULL(@viID_ACCION,''))+','
		+CONVERT(VARCHAR,ISNULL(@viID_MODULO,''))+','
		+CONVERT(VARCHAR,ISNULL(@piCOD_ACCION,''))+','
		+CONVERT(VARCHAR,ISNULL(@piCOD_MODULO,''))+','
		+CONVERT(VARCHAR,ISNULL(@piCOD_EMPRESA,''))+','
		+''''+ISNULL(@psCOD_SISTEMA,'')+''''+','
		+''''+ISNULL(@psCOD_USUARIO,'No Definido')+''''+','
		+CONVERT(VARCHAR,DATEPART(YEAR,GETDATE()))+','
		+''''+ISNULL(REPLACE(@psDATO_ACTUALIZADO,'''',''''''),'')+''''+','
		+''''+ISNULL(@psDATO_ELIMINADO,'')+''''+','
		+''''+ISNULL(REPLACE(@psDATO_NUEVO,'''',''''''),'')+''''+','
		+''''+ISNULL(@psDES_REGISTRO,'')+''''+','
		+CONVERT(VARCHAR,GETDATE(),112)+','
		+''''+CONVERT(VARCHAR,GETDATE(),109)+''''+','
		+''''+SUBSTRING((CONVERT(VARCHAR,GETDATE(),114)),1,5)+''','
		+CONVERT(VARCHAR,DATEPART(MONTH,GETDATE())) +')'

	EXEC  ( @csSENTENCIA_INSERTAR)

END


GO
