USE [SICAD_CONSOLIDADO]
GO

/* TABLAS */

GRANT SELECT ON dbo.AUX_CUOTAS_MAX_DIAS_ATRASO_CAPITAL TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_CUOTAS_MAX_DIAS_ATRASO_INTERES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_FN_SALDO_GRUPO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_MODIFICACIONES_HISTORICAS_CIC TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_OCE TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_OCS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_PROVISION_OPERACIONES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_RPT_ASIENTO_CONTABLE_814_619_DETALLE TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_RPT_DEUDORES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_RPT_ESTADO_COLOCACIONES_POR_AREA_Y_DIVISION TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_RPT_MAYOR_PROVISION_DETALLE TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_RPT_MAYOR_PROVISION_GENERAL TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_RPT_MOROSIDAD_REGION_DETALLE TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_RPT_MOROSIDAD_REGION_GENERAL TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_SICAD_TH_CREDITO_PRINCIPAL_DIRECTO_MES_ANTERIOR TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_SUMA_SALDOS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_TD_CLIENTE TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_TIPO_CAMBIO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_TIPO_CAMBIO_CONTEO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.AUX_TIPO_CAMBIO_LLAVES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.BIENES_REALIZABLES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.BIENES_REALIZABLES_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.BIENES_REALIZABLES_NO_REPORTADOS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.BIENES_REALIZABLES_NO_REPORTADOS_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.BIENES_REALIZABLES_OPERACIONES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.BIENES_REALIZABLES_OPERACIONES_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.bloque_respaldo TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.CATALOGO_CUENTAS_BV TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.CUENTAS_COBRAR_NO_ASOCIADAS_OPERACIONES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.CUENTAS_COBRAR_NO_ASOCIADAS_OPERACIONES_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.CUOTAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.CUOTAS_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.CUOTAS_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.CuotasOperacion TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.DEUDORES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.DEUDORES_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.DEUDORES_RECALIFICADOS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.DEUDORES_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.ENTIDAD_CONTABLE_ESTADOS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.EXCEL TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.FACTURAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_GRAVAMEN TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_GRAVAMEN_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_GRAVAMEN_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_GRAVAMEN TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_GRAVAMEN_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_GRAVAMEN_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_LISTA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_LISTA_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_LISTA_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_PRIORIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_PRIORIDAD_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_PRIORIDAD_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIA_OPERACION_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_CARTA_CREDITO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_CARTA_CREDITO_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION_POLIZA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_CARTAS_CREDITO_IMPORTACION_POLIZA_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FACTURAS_CEDIDAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FACTURAS_CEDIDAS_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FIDEICOMISO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FIDEICOMISO_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA_GRAVAMEN TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FIDEICOMISO_GARANTIA_FIDEICOMETIDA_GRAVAMEN_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FIDUCIARIAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_FIDUCIARIAS_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_REALES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_REALES_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_REALES_POLIZA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_REALES_POLIZA_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_REALES_POLIZA_RESP_SP TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_REALES_RESP_SP TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_VALORES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GARANTIAS_VALORES_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.GENERAL_BV TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.LOG_GARANTIAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.MONTO_MITIGADOR_CALCULADO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.MORA_DEUDOR TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_ACTIVIDAD_ECONOMICA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_ACTIVIDAD_ECONOMICA_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_ACTIVIDAD_ECONOMICA_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_CODEUDORES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_CODEUDORES_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_CODEUDORES_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_CREDITO_SINDICADO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_CREDITO_SINDICADO_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_CREDITO_SINDICADO_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_MODIFICACION TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_MODIFICACION_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_MODIFICACION_OPERACIONES_CANCELADAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_MODIFICACION_OPERACIONES_CANCELADAS_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_MODIFICACION_OPERACIONES_CANCELADAS_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_MODIFICACION_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_NATURALEZA_GASTO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_NATURALEZA_GASTO_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_NATURALEZA_GASTO_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_NO_REPORTADAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_NO_REPORTADAS_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_OPERACION_ESPECIAL TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_OPERACION_ESPECIAL_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_OPERACION_ESPECIAL_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_ORIGEN_RECURSOS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_ORIGEN_RECURSOS_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_ORIGEN_RECURSOS_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_SALDOS_CUENTAS_COBRAR TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_SALDOS_CUENTAS_COBRAR_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.OPERACIONES_SALDOS_CUENTAS_COBRAR_RESP_SB TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.PADRON TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.PERSONAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.PERSONAS_ENTIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.PLANO_BCR TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.PRIDEUCTL TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.SICAD_SALDO_BV TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.SISACT TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.SUGEF_COMPORTAMIENTO_PAGO_HISTORICO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.SUGEF_PADRON_EMISION TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.SUGEF_PADRON_EMISOR TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.SUGEF_PADRON_FISICA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.SUGEF_PADRON_INSTRUMENTO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.SUGEF_PADRON_JURIDICA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TEMP_MES_ACTUAL TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TEMP_MES_ANTERIOR TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_ADEUDADOS_FIDEICOMISO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_CASTIGOS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_EQUIVALENCIAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_ESTIMACION TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GAR_DUPLICADAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GAR_UNICAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GARANTIA_FIDEICOMETIDAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GARANTIA_FIDEICOMETIDAS_RESPONSABILIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GARANTIA_FIDEICOMISOS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GARANTIA_FTIDAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GARANTIA_GRAVAMEN TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GARANTIA_RESPONSABILIDAD TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GENERICA_ESPECIFICA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_GIROS_LINEA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_MONTO_TOTAL_ADEUDADO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_OPE_DUPLICADAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_OPE_UNICAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_REEVALUACION TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_RESPONSABILIDAD_LINEA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_SALDOS_ESTIMACION TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_SEMESTRES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_SEMESTRES_CONTROL TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_VAG TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_VAPG TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_CALCULOS_VAPG_FIDAS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_DEUDOR_GIE TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_DEUDORES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_DEUDORES_RECALIFICADOS TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_GARANTIA_OPERACION_GARANTIA_FIDEICOMETIDA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_GARANTIA_OPERACION_LISTA TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_GARANTIAS_REALES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_GRUPO_DEUDORES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_GRUPO_INTEGRANTES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_OPERACIONES TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_RESP_CALCULOS_MONTO_TOTAL_ADEUDADO TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_RESP_CALCULOS_VAG TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_RESP_CALCULOS_VAPG TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.TMP_SALDO_DEUDOR TO RAP_AccesoReportes
GO
GRANT SELECT ON dbo.VOFTEMP TO RAP_AccesoReportes
GO


/* VISTAS */

GRANT SELECT ON dbo.VW_SALDO_BASE_PROV TO RAP_AccesoReportes
GO

