USE [FACTOREO]
GO

/* TABLAS */

GRANT SELECT ON cf.CF_CALENDARIOS TO RAP_AccesoSICAD
GO
GRANT SELECT ON cl.CL_ACTIVIDAD_ECONOMICA TO RAP_AccesoSICAD
GO
GRANT SELECT ON cl.CL_ID_CLIENTES TO RAP_AccesoSICAD
GO
GRANT SELECT ON cl.CL_PERSONAS_FISICAS TO RAP_AccesoSICAD
GO
GRANT SELECT ON cl.CL_PERSONAS_JURIDICAS TO RAP_AccesoSICAD
GO
GRANT SELECT ON df.DF_DATOS_X_PRODUCTO TO RAP_AccesoSICAD
GO
GRANT SELECT ON df.DF_DESEMBOLSOS TO RAP_AccesoSICAD
GO
GRANT SELECT ON df.DF_FACTURAS TO RAP_AccesoSICAD
GO
GRANT SELECT ON df.DF_LINEA_CREDITO TO RAP_AccesoSICAD
GO
GRANT SELECT ON df.DF_OPERACIONES TO RAP_AccesoSICAD
GO


/* VISTAS */

GRANT SELECT ON dbo.VW_OPERACIONES_FACTOREO TO RAP_AccesoSICAD
GO




