USE [SICAD_TANQUE]
GO

/* TABLAS */

GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ASIENTO_CONTABLE_AJUSTES TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ASIENTO_CONTABLE_BCR TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ASIENTO_CONTABLE_BD_SICAD TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_AGRUPACION_RIDEUCTL TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_BLOQUE_PERSONAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_DESEMBOLSOS_SISACT TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_DEUDOR_OPERACIONES TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_FACTURAS_OPERACIONES_FACTOREO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_OPERACIONES_FACTOREO_MONTO_DESEMBOLSADO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_OPERACIONES_TIPO6 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_PERSONAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_RANGO_SALARIO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.AUX_VW_OPERACIONES_FACTOREO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_01 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_02 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_03 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_619 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_619_01_LINEAS_DE_CREDITO_BCR TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_619_01_LINEAS_DE_CREDITO_BCR_FIN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_619_01_LINEAS_DE_CREDITO_SICAD TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_619_01_LINEAS_DE_CREDITO_SICAD_FIN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_01_LINEAS_DE_CREDITO_BCR TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_01_LINEAS_DE_CREDITO_BCR_FIN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_01_LINEAS_DE_CREDITO_SICAD TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_01_LINEAS_DE_CREDITO_SICAD_FIN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_02_CREDITOS_PENDIENTES_BCR TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_02_CREDITOS_PENDIENTES_BCR_FIN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_02_CREDITOS_PENDIENTES_SICAD TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_02_CREDITOS_PENDIENTES_SICAD_FIN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_03_SOBREGIROS_PENDIENTES_BCR TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_03_SOBREGIROS_PENDIENTES_BCR_FIN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_03_SOBREGIROS_PENDIENTES_SICAD TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.Balance_CTA_814_03_SOBREGIROS_PENDIENTES_SICAD_FIN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.BANKTRADE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.CATALOGO_CUENTAS_BV TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.DISTRIBUCION_OFICINAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.ESTADOS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EXCEL_AUTORIZADO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EXCEL_CAPACIDAD_PAGO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EXCEL_GENERADOR_DIVISAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EXCEL_GENERO_CLIENTE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EXCEL_PlantillaFideicomisos TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EXCEL_PlantillaFideicomisos_PRE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EXCEL_PRODUCTO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.EXCEL_TIPO_GARANTIA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.GENERAL_BV TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.HOMOLOGACION_RUC TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MG_GRUPOS_TASA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MG_TIPO_BIEN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MOROSIDAD_POR_REGION_DETALLE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.MOROSIDAD_POR_REGION_GENERAL TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON [dbo].[OLE DB Destination] TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.OPERACIONES_FACTOREO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PR_CALIFICACION_CARTERA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PRE_AGRUPACION_RIDEUCTL TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.PRE_RIDEUCTL TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_CARTAS_CREDITO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_CC_IMPORTACION TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_CC_IMPORTACION_POLIZAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_FACTURAS_CEDIDAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_FIDEICOMISO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_FIDUCIARIAS TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_FISO_FIDEICOMETIDO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_FISO_FIDO_GRAVAMEN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_GAROPER TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_GAROPER_FIDEICOMETIDO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_GAROPER_FIDO_GRAVAMEN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_GAROPER_GRAVAMEN TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_GAROPER_LISTA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_GAROPER_PRIORIDAD TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_REALES TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_REALES_POLIZA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_SALDO_BV TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.SICAD_VALORES TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TEMP_SICAD_GAROPER_LISTA TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TEMP_SICAD_VALORES TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_ADI_814 TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_ADI_814_PRE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_BCRTARJ TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_BCRTARJ_ESTADO_OPE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_BCRTARJ_PRE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_CONCOMP TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_CONCOMP_PRE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_CONSAC TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_CONSAC_PRE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_CONSAC_TEMP TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_EXCEL TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_EXCEL_HOMOLOGADO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_EXCEL_PRE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_PLANO_BCR TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_RIDEUCTL TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_RIDEUCTL_PRE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_SISACT TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_SISACT_PRE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_SUJFLU TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.TXT_SUJFLU_PRE TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.VW_OPERACIONES_FACTOREO TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.vwrsgsgrcoberturapoliza TO RAP_AccesoIntegracion
GO
GRANT SELECT, INSERT, DELETE, UPDATE ON dbo.vwrsgsgrpoliza TO RAP_AccesoIntegracion
GO


/* FNs */

GRANT EXECUTE ON Obtiene_Rango_Estado TO RAP_AccesoIntegracion
GO



